### ISSUE TITLE
Unicode Emoji Regexp on numbers

### ISSUE THREAD

**Issue by XavierMeunier** [janlelis/unicode-emoji#6]
Hi,

I find your gem and it seems awesome to spot emojis but I've got some difficulties with it.

When I use `Unicode::Emoji::REGEX_ANY`, it matches numbers too (as described in the ReadMe).
To me, a number is not an emoji (but I'm probably wrong as I'm the first one to put this as an issue)

<img width="438" alt="capture d ecran 2019-02-13 a 14 27 09" src="https://user-images.githubusercontent.com/2570972/52714970-88055d00-2f9b-11e9-86ac-8e817ce79481.png">

What would be the right regexp to match a maximum of emojis without numbers or "regular" characters ?

**Comment by janlelis** [comment]
Hi @XavierMeunier, I would recommend using `Unicode::Emoji::REGEX` or `Unicode::Emoji::REGEX_VALID`. The latter is more future-proof, since it will catch currently unknown emoji zwj sequences (= multiple independent emoji combined with ZWJ codepoint) - but this will of course also catche emoji zjw sequence that do not exist.

The `REGEX_ANY` matches all *emoji-related* codepoints which often is not what you want. Digits are emoji-related, because they will show up as an emoji when followed by the VS16 codepoint:

$ uniscribe "5️"       

    ---- ├┬ 5️		├┬ Composition: DIGIT FIVE (emoji style)
    0035 │├─ 5		│├─ DIGIT FIVE
    FE0F │└─ VS16		│└─ VARIATION SELECTOR-16

**Comment by janlelis** [comment]
Also see this other answer: https://github.com/janlelis/unicode-emoji/issues/4#issuecomment-441433824
